### ISSUE TITLE
tag webpacker:css writes css and js tags

### ISSUE THREAD

**Issue by joroe** [jimblue/statamic-addon-webpacker-hub#2]
Problem is WebpackerTags.php, Line 126, I think.

**Comment by jimblue** [comment]
Can you give me more information please?

**Comment by jimblue** [comment]
In development mode it's normal that `webpacker:css` output a **css** and a **js** tag.
The javascript part is need to hot reload you stylesheet will developing a theme.
Obviously this is not happening in production mode 😉
